#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd polkit-kde-agent udiskie)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
/usr/lib/polkit-kde-authentication-agent-1 &
# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &
# Apply themes
~/.config/hypr/scripts/gtkthemes &
# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

exec udiskie &
exec hyprpaper &
