#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Wofi Powermenu

## Files
CONFIG="$HOME/.config/openbox/rofi/config"
STYLE="$HOME/.config/openbox/rofi/style.css"
COLORS="$HOME/.config/openbox/rofi/colors"

## rofi Command
rofi_command="rofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=300 --height=165 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

uptime=$(uptime -p | sed -e 's/up //g')

## Entries
shutdown=" Shutdown"
reboot=" Restart"
lock=" Lock"
suspend=" Sleep"
logout=" Logout"

# Ask for confirmation
cdialog() {
	yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

# Variable passed to rofi
open_menu() {
	options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

	chosen="$(echo -e "$options" | $rofi_command --prompt "UP - $uptime")"
	case $chosen in
	$shutdown)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl poweroff
		else
			exit
		fi
		;;
	$reboot)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl reboot
		else
			exit
		fi
		;;
	$lock)
		~/.config/openbox/scripts/lockscreen
		;;
	$suspend)
		cdialog
		if [[ "$?" == 0 ]]; then
			mpc -q pause
			amixer set Master mute
			~/.config/openbox/scripts/lockscreen
			systemctl suspend
		else
			exit
		fi
		;;
	$logout)
		cdialog
		if [[ "$?" == 0 ]]; then
			kill -9 -1
		else
			exit
		fi
		;;
	esac
}

if [[ ! $(pidof rofi) ]]; then
	open_menu
else
	pkill rofi
fi
